create table if not exists users
(
    id       bigint primary key generated by default as identity,
    name     varchar(25) not null,
    email    varchar(25) not null unique,
    password varchar(255) not null
);
insert into users (name, email, password) VALUES ('tom','tom@mail.ru', 'qwe');

select * from users;

create table if not exists post
(
    id         bigint primary key generated by default as identity,
    message    varchar(255),
    hider      varchar(50),
    user_id    bigint,
    created_at date,
    updated_at date,
    foreign key (user_id) references users (id)
);