spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SocialMediaAPI
    username: user
    password: 123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20

  liquibase:
    enabled: false
    change-log: db/changelog.yaml

  jackson:
    date-format: yyyy-MM-dd

  jpa:
    properties.hibernate:
      #     ddl-auto: create $ validate
      show_sql: true
      format_qsl: true
    show-sql: true

  security:
    user:
      name: user
      password: 123

logging:
  level:
    root: info
  file:
    name: test.log
    path: /

server:
  port: 8081