#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/SocialMediaAPI
#    username: user
#    password: 123
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#application:
#  security:
#    jwt:
#      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

#security:
#  user:
#    name: user
#    password: 123
#
#liquibase:
#  enabled: false
#  change-log: db/changelog.yaml
#
#logging:
#  level:
#    root: info
#    file:
#    name: test.log
#    path: /
#
#server:
#  port: 8081